/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.9/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "springboot-device-data-pipeline"
include(
    "dependency-bom",
    "commons-test",
    "commons-core",
    "commons-ms-core",
    "commons-ms-client",
    "ingester-ms",
    "model-ms",
    "recommendation-ms",
    "messages",
    "model-ms-client"
)
