application.ingester:
  mqtt:
    - name: RTL433
      host: 10.10.30.23
      port: 1883
      clientId: rtl433-client-${random.uuid}
      topic: rtl_433/c568f8b433e2/events

spring.rabbitmq:
  connection-timeout: 5s
  host: localhost
  username: admin
  password: secret
  port: 5672