spring.application.name: ingester-ms
spring.profiles.active: ${PROFILE:local}

server.port: ${SERVER_PORT:3041}

info:
  app.name: ${spring.application.name}
  app.version: ${version:project.version}
  app.profile: ${spring.profiles.active}

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health,info
  health.mongo.enabled: false

management.info:
  build.enabled: true
  env.enabled: true
  java.enabled: true
  os.enabled: true

logging.level:
  org.springframework: INFO

spring.cloud.stream.bindings:
  dataProducer-out-0:
    destination: iot.data

spring.cloud.stream.rabbit.bindings:
  dataProducer-out-0:
    producer:
      autoBindDlq: false