spring.application.name: model-ms
spring.profiles.active: ${PROFILE:local}

server.port: ${SERVER_PORT:3043}

info:
  app.name: ${spring.application.name}
  app.version: ${version:project.version}
  app.profile: ${spring.profiles.active}

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health,info
  health.mongo.enabled: false

management.info:
  build.enabled: true
  env.enabled: true
  java.enabled: true
  os.enabled: true

logging.level:
  org.springframework: INFO

spring.cloud.stream:
  default:
    binder: rabbit
    contentType: application/json

spring.cloud.stream.bindings:
  iotData-in-0:
    destination: iot.data

spring.cloud.stream.rabbit.bindings:
  iotData-in-0:
    consumer:
      autoBindDlq: false

# App-specific
app:
  dedupe:
    cache-ttl-seconds: 60             # in-memory TTL to suppress frequent duplicate DB writes
    cache-max-size: 10_000
  fingerprint:
    bucket-duration-minutes: 60       # per-hour windows (60 minutes)
  recommendation:
    hourly-count-threshold: 100      # sample: if fingerprint bucket count >= this -> recommend
    min-unique-properties: 3